version: '3'
services:
    app:
        build: .
        ports:
            - 5080:5080
        environment: 
            PORT: 5080
        volumes:
            - ./src:/app/src
volumes:
    nodemodules: {}
